version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
  docker-example:
    build:
      context: .
      dockerfile: Dockerfile_debug
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:8080'
      - '5005:5005'
    env_file:
      - .env
