# curl -v -X POST http://localhost:8080/employee -d '{"name":"Venkateswara", "department":"IT"}' -H 'Content-Type:application/json'
POST http://localhost:8080/employee
Content-Type: application/json

{"name":"Venkateswara", "department":"IT"}

<> 2021-09-01T214421.201.json

###
# curl -v -X POST http://localhost:8080/employee -d '{"name":"Prasanna", "department":"Finance"}' -H 'Content-Type:application/json'
POST http://localhost:8080/employee
Content-Type: application/json

{"name":"Prasanna", "department":"Finance"}

<> 2021-09-01T214421-1.201.json

###
# curl -v http://localhost:8080/employee
GET http://localhost:8080/employee

<> 2021-09-01T214427.200.json

###

# curl -v -X DELETE http://localhost:8080/employee/1
DELETE http://localhost:8080/employee/1

###

# curl -v -X DELETE http://localhost:8080/employee/2
DELETE http://localhost:8080/employee/2

###
